### ISSUE TITLE
Make it possible to use pg-migrator programmatically

### ISSUE THREAD

**Issue by mikl** [Aphel-Cloud-Solutions/pg-migrator#2]
I've been looking for something like `pg-migrator`, and I think this looks really promising, but I find myself struggling to integrate it in our projects, due to there being no easy way to run it from another node program.

This is problematic, since we would need to have a global installation on the server, and we would need to put the database configuration for each server into our deployment scripts.

I would like to have an interface where you could do something like this:

~~~js
var migrator = import('pg-migrator');

migrator.run('postgres://username:password@localhost/testdb', '/path/to/migration/files', '+1');
~~~

This would enable me to just make a simple wrapper script that loaded the configuration file we use for the rest of the application and then feed the database connection and the sql folder into pg-migrator.

I've tried looking around in the code, to see if I could do this easily. Unfortunately, it would require quite a bit of refactoring, which is why I'm posting this, rather than a pull request.

Please let me know if you would be willing to consider such a change – I would be willing to help with the refactoring, if that's any consolation.

**Comment by lkaragol** [comment]
Sorry for latency and thanks for feedback.

Actually pg-migrator is designed as an tool more than a library but you can run it from Node as an process. We're using pg-migrator on our prod. environment with Grunt integration (grunt-shell task) via following script.

```javascript
module.exports = function (grunt) {

    grunt.initConfig({
            pkg: grunt.file.readJSON("package.json"),
            shell: {
                updateDBRevision: {
                    command: "pg-migrator postgres://username:password@a.b.c.d/mydb",
                    options: {
                        execOptions: {
                            cwd: "/root/myapp/migration"
                        }
                    }
                }
            }
        }
    );

    grunt.loadNpmTasks("grunt-shell");
    grunt.loadNpmTasks("grunt-shell-spawn");

    grunt.registerTask("install_server", ["shell:updateDBRevision"]);
};
```

Of course, Grunt is not the only option. You can even run pg-migrator as a child process directly from node.
